title: New bundle
filename: bundle.pdf
hasCoversheets: true
hasTableOfContents: true
enableEmailNotification: false
documents:
  - type: documentSet
    property: /caseDocuments
    filters:
      - property: /documentName
        value: Document 1
