java:
  environment:
    CALLBACK_DOMAIN: ${SERVICE_FQDN}
  keyVaults:
    em-ccd-orchestrator:
      resourceGroup: em-ccd-orchestrator
      secrets:
        - AppInsightsInstrumentationKey
        - microservicekey-em-ccd-orchestrator
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName: